### PR TITLE
hide a few functions that do not need to be part of the public API

### PR DESCRIPTION
**Pull request by LukeWinikates**
related to issues #89 and #98

### CODE REVIEW

**Comment by LukeWinikates** [comment]
@keep94 - not sure if this is exactly what you had in mind, and maybe you had your own reasons for not wanting to hide these methods right away. I figured a PR would give us some code to talk about.

**Comment by keep94** [comment]
Luke. So sorry, I am out on vacation this week. I'll be back Friday
morning. I will have a look at your PR then. Thank you for doing this work.

**Review by keep94 — COMMENTED** [review]
Luke. Thanks for the work. This is a good start.  One question, why didn't you change the HistoLine() function to histoLine()?  

Before committing these changes and going to v1.0.0, we should loop in @oppegard my tech lead to see if he wants anything in the API changed before moving to v1.

**Comment by LukeWinikates** [comment]
> Luke. Thanks for the work. This is a good start. One question, why didn't you change the HistoLine() function to histoLine()?

That's just an oversight :) I'll fix it now

> Before committing these changes and going to v1.0.0, we should loop in @oppegard my tech lead to see if he wants anything in the API changed before moving to v1.

Sounds good to me. I would also like to go ahead and delete the old factory methods prior to v1.

**Comment by LukeWinikates** [comment]
@keep94 - I hid those methods and also changed `histo` to `histogram` in several places. Thanks for taking a look at this!

**Review by oppegard — APPROVED** [review]
Thanks!

**Pull request merged**
